openapi: 3.0.0
info:
  title: Keugeugeuk Backend API
  version: 1.0.0
servers:
  - url: https://{gateway_id}.gateway.dev
paths:
  /users:
    get:
      summary: Get user list
      operationId: listUsers
      responses:
        '200':
          description: OK
  /lotto:
    post:
      summary: Create lotto request
      operationId: createLotto
      responses:
        '200':
          description: OK
