swagger: '2.0'
info:
  title: Keugeugeuk User API
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /users:
    post:
      summary: post user data
      operationId: registerUsers
      x-google-backend:
        address: https://user-service-994769112985.asia-northeast1.run.app/users
        protocol: h2
      responses:
        200:
          description: OK
  /users/{id}:
    get:
      summary: Get user by ID
      operationId: getUser
      parameters:
        - name: id
          in: path
          required: true
          type: string
      x-google-backend:
        address: https://user-service-994769112985.asia-northeast1.run.app/users/{id}
        protocol: h2
      responses:
        200:
          description: OK
    delete:
      summary: delete user
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          type: string
      x-google-backend:
        address: https://user-service-994769112985.asia-northeast1.run.app/users/{id}
        protocol: h2
      responses:
        200:
          description: OK
  /users/{id}/points:
    post:
      summary: update user's points
      operationId: updateUserPoints
      parameters:
        - name: id
          in: path
          required: true
          type: string
      x-google-backend:
        address: https://user-service-994769112985.asia-northeast1.run.app/users/{id}/points
        protocol: h2
      responses:
        200:
          description: OK
  /users/kakao:
    post:
      summary: register kakao users
      operationId: registerKakaoUsers
      x-google-backend:
        address: https://user-service-994769112985.asia-northeast1.run.app/users/kakao
        protocol: h2
      responses:
        200:
          description: OK
  /lifetips:
    get:
      summary: "Get YouTube life tips"
      operationId: "getLifeTips"
      x-google-backend:
        address: https://lifetips-service-994769112985.asia-northeast1.run.app/lifetips
        protocol: h2
      parameters:
        - name: q
          in: query
          required: true
          type: string
      responses:
        200:
          description: "OK"
