name: Deploy API Gateway

on:
  push:
    branches:
      - main
    paths:
      - openapi.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # - name: Set up gcloud
      #   uses: google-github-actions/setup-gcloud@v2
      #   with:
      #     project_id: ${{ secrets.GCP_PROJECT_ID }}
      #     service_account_key: ${{ secrets.GCP_SA_KEY }}
      #     export_default_credentials: true
      - name: Decode and auth with GCP
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > $HOME/gcp-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
          gcloud config set project keugeugeuk-backend
          gcloud auth list
    
      - name: Test GCS Access
        run: |
          gsutil ls gs://keugeugeuk-openapi/
  
      # - name: Upload OpenAPI spec to GCS
      #   run: |
      #     gsutil cp openapi.yaml gs://keugeugeuk-openapi/openapi.yaml

      # - name: Deploy API Gateway Config
      #   run: |
      #     CONFIG_ID=keugeugeuk-backend-config-$(date +%Y%m%d%H%M%S)
      #     gcloud api-gateway api-configs create $CONFIG_ID \
      #       --api=keugeugeuk-backend-api \
      #       --openapi-spec=gs://keugeugeuk-openapi/openapi.yaml \
      #       --project=${{ secrets.GCP_PROJECT_ID }} \
      #       --backend-auth-service-account=keugeugeuk-backend@appspot.gserviceaccount.com
          
      #     gcloud api-gateway gateways update keugeugeuk-backend-gateway \
      #       --api=keugeugeuk-backend-api \
      #       --api-config=$CONFIG_ID \
      #       --location=asia-northeast3 \
      #       --project=${{ secrets.GCP_PROJECT_ID }}
